package com.tmtai.web.banhang.thietbimaytinh.entity;
// Generated Nov 26, 2017 2:38:55 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "thietbimaytinh")
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String fristname;
	private String birthday;
	private String address;
	private String email;
	private String phone;
	private String gender;
	private int enable;
	private String role;
	private String lastname;

	public Users() {
	}

	public Users(String username, String password, String fristname, String birthday, String address, String email,
			String phone, String gender, int enable, String role, String lastname) {
		this.username = username;
		this.password = password;
		this.fristname = fristname;
		this.birthday = birthday;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.gender = gender;
		this.enable = enable;
		this.role = role;
		this.lastname = lastname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fristname", nullable = false, length = 64)
	public String getFristname() {
		return this.fristname;
	}

	public void setFristname(String fristname) {
		this.fristname = fristname;
	}

	@Column(name = "birthday", nullable = false, length = 45)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "gender", nullable = false, length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "enable", nullable = false)
	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	@Column(name = "role", nullable = false, length = 32)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "lastname", nullable = false, length = 64)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

}
